version: "3"
services:
  api:
    image: api:latest
    container_name: api_latest
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      HOST: mongodb
      PORT: 27017
      DATA: test
      USERNAME: root
      PASSWORD: example

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
